### ISSUE TITLE
doesn't build with boost-libs-1.67 in FreeBSD-11.1-p9. but does with 1.66

### ISSUE THREAD

**Issue by lisergey** [graft-project/GraftNetwork#122]
after upgrading boost-libs to 1.67 on FreeBSD-11.1-p9 build gets broken:
```
[ 32%] Building CXX object src/wallet/CMakeFiles/obj_wallet.dir/api/wallet.cpp.o                                                                                                                                               
/var/GraftNetwork/src/wallet/api/wallet.cpp:1296:45: error: no matching constructor for initialization of                                                                                                                   
      'boost::posix_time::milliseconds' (aka 'subsecond_duration<boost::posix_time::time_duration, 1000>')                                                                                                                     
            boost::posix_time::milliseconds wait_for_ms(m_refreshIntervalMillis);                                                                                                                                              
                                            ^           ~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                
/usr/local/include/boost/date_time/time_duration.hpp:270:30: note: candidate constructor                                                                                                                                       
      (the implicit copy constructor) not viable: no known conversion from 'std::atomic<int>' to 'const                                                                                                                        
      boost::date_time::subsecond_duration<boost::posix_time::time_duration, 1000>' for 1st argument                                                                                                                           
  class BOOST_SYMBOL_VISIBLE subsecond_duration : public base_duration                                                                                                                                                         
                             ^                                                                                                                                                                                                 
/usr/local/include/boost/date_time/time_duration.hpp:270:30: note: candidate constructor                                                                                                                                       
      (the implicit move constructor) not viable: no known conversion from 'std::atomic<int>' to                                                                                                                               
      'boost::date_time::subsecond_duration<boost::posix_time::time_duration, 1000>' for 1st argument                                                                                                                          
/usr/local/include/boost/date_time/time_duration.hpp:286:59: note: candidate template ignored: disabled by                                                                                                                     
      'enable_if' [with T = std::__1::atomic<int>]                                                                                                                                                                             
                                typename boost::enable_if<boost::is_integral<T>, void>::type* = 0) :                                                                                                                           
                                                          ^                                                                                                                                                                    
In file included from /var/GraftNetwork/src/wallet/api/wallet.cpp:32:                                                                                                                                                       
In file included from /var/GraftNetwork/src/wallet/api/wallet.h:35:                                                                                                                                                         
In file included from /var/GraftNetwork/src/wallet/wallet2.h:42:                                                                                                                                                            
In file included from /var/GraftNetwork/src/cryptonote_basic/account.h:33:                                                                                                                                                  
In file included from /var/GraftNetwork/src/cryptonote_basic/cryptonote_basic.h:42:                                                                                                                                         
/var/GraftNetwork/src/serialization/binary_archive.h:194:28: warning: shift count >= width of type                                                                                                                          
      [-Wshift-count-overflow]                                                                                                                                                                                                 
      if (1 < sizeof(T)) v >>= 8;                                                                                                                                                                                              
                           ^   ~                                                                                                                                                                                               
/var/GraftNetwork/src/serialization/binary_archive.h:187:5: note: in instantiation of function template                                                                                                                     
      specialization 'binary_archive<true>::serialize_uint<unsigned char>' requested here                                                                                                                                      
    serialize_uint(static_cast<typename boost::make_unsigned<T>::type>(v));                                                                                                                                                    
    ^                                                                                                                           
/var/GraftNetwork/src/serialization/binary_archive.h:227:5: note: in instantiation of function template                                                                                                                     
      specialization 'binary_archive<true>::serialize_int<unsigned char>' requested here                                                                                                                                       
    serialize_int(t);                                                                                                                                                                           
    ^                                                                                                                           
1 warning and 1 error generated.                                                                                                                                                                                               
*** Error code 1                                                                                                         
```
fresh new `git clone https://github.com/graft-project/GraftNetwork.git` before build
downgrading back to boost-libs-1.66 however, fixes it, build finishes and graftnoded runs smoothly.

```
FreeBSD-11.1-p9# pkg version -vl "<"
boost-libs-1.66.0_1                <   needs updating (index has 1.67.0_1)
```
I'd be glad to test fixes

**Comment by theck5263** [comment]
To use the latest Boosts file 1.67 work around is to add this .load() below as an example
boost::posix_time::milliseconds wait_for_ms(m_refreshIntervalMillis.load());

**Comment by lisergey** [comment]
@theck5263, would you please make diff?
I'd be glad to test it

**Comment by theck5263** [comment]
@lisergey 
\src\wallet\api\wallet.cpp Line 1296 Needs to look like this.
boost::posix_time::milliseconds wait_for_ms(m_refreshIntervalMillis.load());
![wallet-cpp](https://user-images.githubusercontent.com/40315039/41503036-322670b0-720c-11e8-8cb6-035675838d6c.jpg)

Also see my latest fault item13, i cant get latest distro of Graft Network to fully comply it hangs at Bcrypt section, i have followed install guide to the letter even pacman instal Bcrpyt seperate but it still fails, this is on latest Msys MinGw install with latest packages!

**Comment by lisergey** [comment]
@theck5263, that worked!! Thank you!
the diff is
```
--- wallet.cpp-orig     2018-07-17 18:37:30.000000000 +0300
+++ wallet.cpp  2018-07-21 02:47:29.482480000 +0300
@@ -1293,7 +1293,7 @@
         // if auto refresh enabled, we wait for the "m_refreshIntervalSeconds" interval.
         // if not - we wait forever
         if (m_refreshIntervalMillis > 0) {
-            boost::posix_time::milliseconds wait_for_ms(m_refreshIntervalMillis);
+           boost::posix_time::milliseconds wait_for_ms(m_refreshIntervalMillis.load());
             m_refreshCV.timed_wait(lock, wait_for_ms);
         } else {
             m_refreshCV.wait(lock);
```
BTW, it does build with CLANG6 from FreeBSD-11.2-RELEASE and does not with GCC8
