### ISSUE TITLE
Does not build with boost 1.67.0

### ISSUE THREAD

**Issue by baskinsy** [graft-project/GraftNetwork#150]
Hello I'm experiencing a similar issue on my Opensuse Tumbleweed system

```
In file included from /home/stratos/bin/GraftNetwork-1.2.2/contrib/epee/include/misc_log_ex.h:36,
                 from /home/stratos/bin/GraftNetwork-1.2.2/contrib/epee/src/mlog.cpp:33:
/home/stratos/bin/GraftNetwork-1.2.2/contrib/epee/include/syncobj.h:37:10: fatal error: boost/thread/v2/thread.hpp: No such file or directory
 #include <boost/thread/v2/thread.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [contrib/epee/src/CMakeFiles/epee.dir/build.make:89: contrib/epee/src/CMakeFiles/epee.dir/mlog.cpp.o] Error 1
make[3]: Leaving directory '/home/stratos/bin/GraftNetwork-1.2.2/build/release'
make[2]: *** [CMakeFiles/Makefile2:372: contrib/epee/src/CMakeFiles/epee.dir/all] Error 2
make[2]: Leaving directory '/home/stratos/bin/GraftNetwork-1.2.2/build/release'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/stratos/bin/GraftNetwork-1.2.2/build/release'
make: *** [Makefile:63: release-all] Error 2
```

https://github.com/monero-project/monero/issues/3663

Maybe is easy to fix as I can see from the monero issue.

**Comment by jagerman** [comment]
See PR #140
